- docs/source/conf.py
- pyproject.toml
readthedocs doesnt seem to natively support git LFS.
> add sphinx_lfs_content extension

- belay/device.py
- belay/inspect.py
- tests/conftest.py
- tests/test_inspect.py
- tests/test_inspect/foo.py
* previously we just assumed that the `@device.task` and `@device.thread` decorator only took up one line. This PR fixes this assumption.
* this PR strips multiple decorators, but still won't properly handle multiple device registration. Currently each registration goes through properly thanks to `inspect.unwrap` and `functools.wraps`, but only the last device gets the executor assigned.
> Robust decorator

- .flake8
- .pre-commit-config.yaml
- README.rst
- belay/__init__.py
- belay/device.py
- docs/source/Quick Start.rst
- docs/source/api.rst
- docs/source/conf.py
- examples/08_multiple_devices/README.rst
- examples/08_multiple_devices/main.py
- tests/test_device.py
This is basic multiple device support for `task` and `thread` decorators.
Currently, a shortcoming is that devices are invoked sequentially, when they could really be invoked at (more or less) the same time. However, this probably involves moving the serial interface to asyncio or similar, which for the current time might complicate the codebase unnecessarily. So, for now, devices will be invoked sequentially, and if a need comes to move to asyncio, we can figure that out later.
> Multiple device support

- belay/device.py
- docs/source/How Belay Works.rst
- tests/test_device.py
- change belay prefix from `__belay_` to` _belay_`.
- change `json_decorator` to `__belay_json` to reduce chance of name collision.
- reduce whitespace in returned json data.
- rename `hash_remote_file` to `__belay_hash_file` to reduce chance of name collision. Don't invoke via `task` to circumvent double prefix.
> Misc Tweaks

- belay/__init__.py
- belay/device.py
- docs/source/How Belay Works.rst
- docs/source/api.rst
- examples/03_read_adc/README.rst
- tests/test_device.py
Swap out json serialization/deserialization in favor of `repr` and `ast.literal_eval`. This allows for `set` and `bytes` to be passed between device and host.
> Byte set support

- .flake8
- .pre-commit-config.yaml
- belay/device.py
- belay/snippets/convenience_imports.py
- belay/snippets/startup.py
- belay/snippets/sync_begin.py
- belay/snippets/sync_end.py
- belay/snippets/try_mkdir.py
- tests/test_device.py
More organized and convenient for developing snippets that are sent to-device adhoc.
> move all from strings in device.py to their own python submodule

- belay/__init__.py
- belay/device.py
- Fixed bad message for `ValueError` in `Device.sync`. Make the reported folder path absolute to aid in debugging.
- Removed `SpecialFilenameError`. `boot.py` and `main.py` dont interfere with Belay operation, and may actually be necessary for some projects.
- Added optional parameter `keep` to `Device.sync`. File(s) provided will NOT be deleted from the device's filesystem if not present in the sync directory. If those files exist in the sync directory, they will overwrite the contents on-device (as usual). Defaults to `["boot.py", "webrep_cfg.py"]`, since these files may contain device-specific configurations.
> Fix sync exception, remove `SpecialFilenameError`, add sync `keep` argument.

- belay/__init__.py
- belay/device.py
- belay/exceptions.py
- belay/pyboard.py
- docs/Makefile
- docs/source/Connections.rst
Problem: Device (for some reason) disconnects, and we want to recover when possible.
Solution:
1. Record all non-task-execution calls to a history.
2. Upon disconnect, attempt to re-connect (in accordance to `attempts`)
3. If reconnection is made, replay the history.
For projects where the board is just a hardware interface (main purpose of Belay), this will get the board back into a state where it can read sensors/output to actuators. If the project requires a more complicated internal device state, this won't really help.
> Connection Retry

- belay/cli/main.py
Blinks LED on board. Useful for identifying which board is associated with which port name.
> Add 'identify' cli command

- .codecov.yml
- belay/cli/__init__.py
- belay/cli/main.py
- belay/device.py
- belay/snippets/sync_begin.py
- pyproject.toml
- tests/cli/test_exec.py
- tests/cli/test_info.py
- tests/cli/test_run.py
- tests/cli/test_sync.py
- tests/conftest.py
- tests/test_device.py
- tests/test_device_sync.py
* [new command] `run` runs a file.
* [new command] `exec` executes a python statement.
* `sync` improvements:
* New argument `dst`; defaults to `"/"`; folder to sync file into.
* New argument `ignore`; uses gitignore pattern matching to ignore files during sync.
* New argument `mpy_cross_binary`; if provided, will compile `.py` files into `.mpy` prior to syncing.
* Can now sync a single file.
* Now keeps all untouched files if `keep=True`.
* Misc bug fixes.
> Mpy cross sync

- belay/device.py
- belay/snippets/emitter_check.py
- belay/snippets/hf.py
- belay/snippets/hf_native.py
- belay/snippets/hf_viper.py
- belay/snippets/ilistdir_circuitpython.py
- belay/snippets/ilistdir_micropython.py
- belay/snippets/startup.py
- belay/snippets/sync_begin.py
- tests/test_device_sync.py
* Adds `device.implementation.emitters`
* Fixes `sync` on devices without native/viper emitters available.
> Emitter check

- .flake8
- belay/inspect.py
- tests/test_inspect.py
- tests/test_inspect/foo.py
Previously, Belay would corrupt a multiline string when obtaining source code.
> Fix multiline string inspect

- belay/__main__.py
- belay/cli/main.py
- belay/cli/run.py
- pyproject.toml
- tests/cli/test_run_exec.py
Adds a pseudo-virtual-environment action to `belay run` if the subsequent port is actually an executable. Currently, just `MICROPYPATH` is set to the local dependencies.
> Belay run pseudo-venv

- belay/pyboard.py
Also `atexit.register` so that if the user forgets to close the device, hopefully subsequent scripts run fine. Fixes broken `rshell` after running belay applications on windows.
> exit_raw_repl() on close

- examples/08B_device_subclassing/README.rst
- examples/08B_device_subclassing/main.py
- examples/08B_device_subclassing/main_multiple_devices.py
- examples/08B_device_subclassing/mydevice.py
- examples/08_device_subclassing/README.rst
Create an alternative to 08_device_subclassing that moves the remote tasks into their own file that could be used in either example. Tested on windows both programs with two RP2040 boards.
Changed the LED for the RP2040 to be board independent. Pin25 is the LED pin only on the non-wifi board. This assumes you are using a version of MicroPython 1.19 from Jan 2023.
> Create an alternative 08B instead of overwriting the existing one

- belay/cli/main.py
- belay/packagemanager/group.py
- belay/packagemanager/models.py
- docs/source/Package Manager.rst
- tests/packagemanager/test_models.py
* Allows dictionary dependency specifications.
* Add dependency option `develop`.
* Additional validator: only 1 dependency source per package can have ``rename_to_init=True``.
> Editable dependencies (develop)

- belay/cli/main.py
- belay/packagemanager/downloaders/common.py
- belay/packagemanager/group.py
Also fixes relative-path dependencies path-resolution when launching from non-project-root directory.
> Fix "belay run micropython" for dependencies where develop=true.

- .github/workflows/tests.yaml
- belay/device.py
- belay/packagemanager/models.py
- belay/pyboard.py
- poetry.lock
- pyproject.toml
I believe in all reasonable situations, the currently running command should be canceled on close. This will also allow the teardown functions to properly function.
> Ctrl c on close

- .flake8
- belay/cli/install.py
- belay/cli/main.py
- belay/cli/run.py
- belay/cli/sync.py
- belay/cli/terminal.py
- belay/device.py
- belay/exceptions.py
- belay/helpers.py
- belay/pyboard.py
- docs/source/Package Manager.rst
- docs/source/api.rst
- tests/cli/test_install.py
- tests/conftest.py
- tests/test_device.py
- tests/test_device_sync.py
* Inclusion of an interactive terminal:
* The `Device` class now has a method `terminal()` that will start a blocking interactive terminal.
* New command: `belay terminal [port]` to open up an interactive terminal with the device.
* Improvements to `belay install`:
* If `--main my_script.py` is specified, device will now restart after installation so that the script will automatically execute.
* New flag `--follow`: after flashing, the output of the main script will be monitored and printed to stdout. Press `ctrl-c` to exit.
> Terminal, post-install reset, post-install monitoring.

- belay/__init__.py
- belay/cli/select.py
- belay/device.py
- belay/device_meta.py
- belay/device_support.py
- belay/exceptions.py
- tests/integration/test_classes.py
- tests/test_device.py
* Allows for implementation-specific decorators by specifying`implementation="implementation name"` in executer decorators.
Example:
```
class MyDevice(Device, skip=True):
@Device.task(implementation="micropython")
def test_task():
return "micropython_task_return_value"
@Device.task(implementation="circuitpython")
def test_task():  # noqa: F811
return "circuitpython_task_return_value"
```
* Add support for executers defined in mixin classes. If the mixin provided methods are to be overloaded, the mixin class must use the `DeviceMeta` metaclass.
* Broke up the large `device.py` module into several modules.
> Implementation specific executers

- .github/workflows/tests.yaml
- belay/device.py
- belay/device_meta.py
- belay/executers.py
- belay/pyboard.py
- pyproject.toml
- tests/integration/test_classes.py
* In the case of device mixins, the `Device` class will automatically be moved to the end of the MRO. This makes name stomping of `setup` and `teardown` and other executers as expected.
* Add `ignore_errors=False` flag to global executers (`setup` and `teardown`). This is particularly useful for `teardown` since it may be invoked before the device is even fully setup.
> Modify MRO order, add ignore_errors=False to global executers.

- belay/cli/common.py
- belay/cli/exec.py
- belay/cli/install.py
- belay/cli/run.py
No need to provide the full trace; caller is only interested in the device-side PyboardException stacktrace.
> Fully remove belay-internal stacktrace for install/run/exec cli commands

- belay/device_sync_support.py
- tests/test_device_sync.py
device.sync wasn't working when the source folder was on a different drive than the temp directory.
I think the intention of the code was to get the path without the drive specifier by getting the relative path of it when compared to the drive specifier. However the temp file driver specifier was being passed through rather than the source file one.
> Fix bug in device.sync that prevented it from working on some drives

- docs/source/Quick Start.rst
I hadn't realized when I ran sync that it would delete all the other files on my device, so I figure it's worth making it clear, especially as a common way of using Thonny is actually to do development directly on the device files, and periodically backup, which is what I had been doing. Luckily I had a recent backup.
> Documentation note that sync deletes all other files on device.

- belay/device.py
- belay/executers.py
- pyproject.toml
- tests/integration/test_function_decorators.py
Addresses #148 . @pdietl can you give this a test? Is the API documentation sufficient?
> Introduce 'trusted' keyword to task decorator for allowing arbitrary response execution.

- .pre-commit-config.yaml
- belay/cli/new.py
- belay/device.py
- belay/device_meta.py
- belay/executers.py
- belay/pyboard.py
- belay/webrepl.py
- docs/source/Package Manager.rst
- pyproject.toml
- tests/conftest.py
- tests/integration/test_function_decorators.py
- tests/test_device.py
- tests/test_inspect.py
Previously the `belay new` CLI command was broken in some installed because there would be a `__pycache__` directory in the template directory. These files are now ignored.
> fix "belay new" CLI command

- belay/_minify.py
- tests/test_minify.py
> Fix minifying strings-in-containers as if they were docstrings.

- belay/pyboard.py
Related: https://github.com/BrianPugh/belay/discussions/171
> skip telnet authentication if username is empty

- .github/workflows/tests.yaml
- .pre-commit-config.yaml
- belay/pyboard.py
- belay/telnetlib.py
significantly speed up telnet by reducing sleep.
> Telnet tweaks; python3.13 compat

- belay/device.py
- tests/test_device.py
@kc64 what do you think of this? I think the only reason I didn't originally dedent before was I didn't know it existed when I originally implemented Belay 😄 .
If someone in the future has issues with this, we can add a `dedent: bool = True` argument to `Device.__call__`, but I don't foresee a real use-case that requires this.
> `dedent` all cmds in `Device.__call__`

- belay/_minify.py
- tests/test_minify.py
Minifying would break expressions that started with a string, like `"a" in {'a', 'b', 'c'}`. This fixes that.
> BUGFIX: fix removal of str if it begins an expression when minifying.

- belay/packagemanager/group.py
I have had issues on windows with some micro python repos. Using utf-8 should be the default I think. 
https://peps.python.org/pep-0686/
> Verify files use encoding utf8
